# Generated by Django 5.2.17 on 2026-08-29 05:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='MQTT Broker', max_length=100)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('broker_host', models.CharField(default='broker.hivemq.com', max_length=255)),
                ('broker_port', models.PositiveIntegerField(default=1883)),
                ('connected_clients', models.PositiveIntegerField(default=0)),
                ('total_alerts_today', models.PositiveIntegerField(default=0)),
                ('total_alerts_this_week', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Status',
                'verbose_name_plural': 'System Statuses',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(help_text='MQTT topic for this zone', max_length=255, unique=True)),
                ('max_distance_meters', models.PositiveIntegerField(default=2500)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Monitoring Zone',
                'verbose_name_plural': 'Monitoring Zones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FiberAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ALARM', 'Alarm'), ('WARNING', 'Warning'), ('NORMAL', 'Normal'), ('OFFLINE', 'Offline')], default='NORMAL', max_length=20)),
                ('distance_meters', models.PositiveIntegerField(blank=True, null=True)),
                ('danger', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Operator notes about this alert')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='dashboard.zone')),
            ],
            options={
                'verbose_name': 'Fiber Alert',
                'verbose_name_plural': 'Fiber Alerts',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='dashboard_f_timesta_24b4db_idx'), models.Index(fields=['status'], name='dashboard_f_status_99e360_idx'), models.Index(fields=['zone'], name='dashboard_f_zone_id_7dafb7_idx')],
            },
        ),
    ]
